name: crusher
description: Crusher App

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  google_sign_in: 4.0.7
  firebase_auth: 0.14.0+5
  flutter_auth_buttons: 0.5.0

  http: 0.12.0+2
  firebase_messaging: 5.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
